#ifndef _SMARTRF_SETTINGS_H_
#define _SMARTRF_SETTINGS_H_

//*********************************************************************************
// Generated by SmartRF Studio version 2.10.0 (build#110)
// The applied template is compatible with CC2640R2 SDK 1.40.xx.xx
// Device: CC2640R2F Rev. 2.5
// 
//*********************************************************************************
#include <driverlib/rf_mailbox.h>
#include <driverlib/rf_common_cmd.h>
#include <driverlib/rf_ble_cmd.h>

// RF Core API commands
extern rfc_CMD_BLE5_RADIO_SETUP_t RF_cmdBle5RadioSetup;
extern rfc_CMD_FS_t RF_cmdFs;
extern rfc_CMD_BLE5_ADV_AUX_t RF_cmdBle5AdvAux;
extern rfc_CMD_SYNC_STOP_RAT_t RF_cmdSyncStopRat;
extern rfc_CMD_SYNC_START_RAT_t RF_cmdSyncStartRat;
extern rfc_CMD_BLE_SCANNER_t RF_cmdBleScanner;


// RF Core API Overrides
extern uint32_t pOverridesCommon[];
extern uint32_t pOverrides1Mbps[];
extern uint32_t pOverrides2Mbps[];
extern uint32_t pOverridesCoded[];


#endif // _SMARTRF_SETTINGS_H_

