//*********************************************************************************
// Generated by SmartRF Studio version 2.10.0 (build#110)
// The applied template is compatible with CC2640R2 SDK 1.40.xx.xx
// Device: CC2640R2F Rev. 2.5
// 
//*********************************************************************************


//*********************************************************************************
// Parameter summary
// Adv. Address: 010203040506 
// Adv. Data: 255 
// BLE Channel: 17 
// Extended Header: 09 09 010203040506 babe 
// Frequency: 2440 MHz
// PDU Payload length:: 30 
// TX Power: 5 dBm 
// Whitening: true 

#include <driverlib/rf_mailbox.h>
#include <driverlib/rf_common_cmd.h>
#include <driverlib/rf_ble_cmd.h>
#include <rf_patches/rf_patch_cpe_bt5.h>
#include "smartrf_settings.h"

// Overrides for CMD_BLE5_RADIO_SETUP
uint32_t pOverridesCommon[] =
{
    // override_ble5_setup_override_common.xml
    // Rx: Set LNA IB trim value based on the selected defaultPhy.mainMode setting. (NOTE: The value 0x8 is a placeholder. The value to use should be set during run-time by radio driver function.)
    ADI_HALFREG_OVERRIDE(0,4,0xF,0x8),
    // Rx: Set LNA IB offset used for automatic software compensation to 0
    (uint32_t)0x00008883,
    // Synth: Use 24 MHz crystal, enable extra PLL filtering
    (uint32_t)0x02010403,
    // Synth: Set fine top and bottom code to 127 and 0
    HW_REG_OVERRIDE(0x4020, 0x7F00),
    // Synth: Configure faster calibration
    HW32_ARRAY_OVERRIDE(0x4004, 1),
    // Synth: Configure faster calibration
    (uint32_t)0x1C0C0618,
    // Synth: Configure faster calibration
    (uint32_t)0xC00401A1,
    // Synth: Configure faster calibration
    (uint32_t)0x21010101,
    // Synth: Configure faster calibration
    (uint32_t)0xC0040141,
    // Synth: Configure faster calibration
    (uint32_t)0x00214AD3,
    // Synth: Decrease synth programming time-out by 64 us (0x0300 RAT ticks = 192 us)
    (uint32_t)0x03000243,
    // Bluetooth 5: Set correct total clock accuracy for received AuxPtr assuming local sleep clock of 50 ppm
    (uint32_t)0x0E490823,
    // override_frontend_id.xml
    (uint32_t)0xFFFFFFFF,
};


// Overrides for CMD_BLE5_RADIO_SETUP
uint32_t pOverrides1Mbps[] =
{
    // override_ble5_setup_override_1mbps.xml
    // Rx: Set LNA IB trim to normal trim value. (NOTE: The value 0x8 is a placeholder. The value to use should be set during run-time by radio driver function.)
    ADI_HALFREG_OVERRIDE(0,4,0xF,0x8),
    // Rx: Configure AGC to use gain table for improved performance
    HW_REG_OVERRIDE(0x6084, 0x05F8),
    (uint32_t)0xFFFFFFFF,
};


// Overrides for CMD_BLE5_RADIO_SETUP
uint32_t pOverrides2Mbps[] =
{
    // override_ble5_setup_override_2mbps.xml
    // Rx: Set LNA IB trim to normal trim value. (NOTE: The value 0x8 is a placeholder. The value to use should be set during run-time by radio driver function.)
    ADI_HALFREG_OVERRIDE(0,4,0xF,0x8),
    (uint32_t)0xFFFFFFFF,
};


// Overrides for CMD_BLE5_RADIO_SETUP
uint32_t pOverridesCoded[] =
{
    // override_ble5_setup_override_coded.xml
    // Rx: Set LNA IB trim to 0xF (maximum)
    ADI_HALFREG_OVERRIDE(0,4,0xF,0xF),
    // Rx: Override AGC target gain to improve performance
    HW_REG_OVERRIDE(0x6088, 0x001B),
    (uint32_t)0xFFFFFFFF,
};


// CMD_BLE5_RADIO_SETUP
// Bluetooth 5 Radio Setup Command for all PHYs
rfc_CMD_BLE5_RADIO_SETUP_t RF_cmdBle5RadioSetup =
{
    .commandNo = 0x1820,
    .status = 0x0000,
    .pNextOp = 0, // INSERT APPLICABLE POINTER: (uint8_t*)&xxx
    .startTime = 0x00000000,
    .startTrigger.triggerType = 0x0,
    .startTrigger.bEnaCmd = 0x0,
    .startTrigger.triggerNo = 0x0,
    .startTrigger.pastTrig = 0x0,
    .condition.rule = 0x1,
    .condition.nSkip = 0x0,
    .defaultPhy.mainMode = 0x0,
    .defaultPhy.coding = 0x0,
    .__dummy0 = 0x00,
    .config.frontEndMode = 0x0,
    .config.biasMode = 0x0,
    .config.analogCfgMode = 0x0,
    .config.bNoFsPowerUp = 0x0,
    .txPower = 0x9330,
    .pRegOverrideCommon = pOverridesCommon,
    .pRegOverride1Mbps = pOverrides1Mbps,
    .pRegOverride2Mbps = pOverrides2Mbps,
    .pRegOverrideCoded = pOverridesCoded,
};

// CMD_FS
// Frequency Synthesizer Programming Command
rfc_CMD_FS_t RF_cmdFs =
{
    .commandNo = 0x0803,
    .status = 0x0000,
    .pNextOp = 0, // INSERT APPLICABLE POINTER: (uint8_t*)&xxx
    .startTime = 0x00000000,
    .startTrigger.triggerType = 0x0,
    .startTrigger.bEnaCmd = 0x0,
    .startTrigger.triggerNo = 0x0,
    .startTrigger.pastTrig = 0x0,
    .condition.rule = 0x1,
    .condition.nSkip = 0x0,
    .frequency = 0x0988,
    .fractFreq = 0x0000,
    .synthConf.bTxMode = 0x0,
    .synthConf.refFreq = 0x0,
    .__dummy0 = 0x00,
    .__dummy1 = 0x00,
    .__dummy2 = 0x00,
    .__dummy3 = 0x0000,
};

// Structure for CMD_BLE5_ADV_AUX.pParams
rfc_ble5AdvAuxPar_t ble5AdvAuxPar =
{
    .pRxQ = 0, // INSERT APPLICABLE POINTER: (dataQueue_t*)&xxx
    .rxConfig.bAutoFlushIgnored = 0x0,
    .rxConfig.bAutoFlushCrcErr = 0x0,
    .rxConfig.bAutoFlushEmpty = 0x0,
    .rxConfig.bIncludeLenByte = 0x0,
    .rxConfig.bIncludeCrc = 0x0,
    .rxConfig.bAppendRssi = 0x0,
    .rxConfig.bAppendStatus = 0x0,
    .rxConfig.bAppendTimestamp = 0x0,
    .advConfig.advFilterPolicy = 0x0,
    .advConfig.deviceAddrType = 0x0,
    .advConfig.targetAddrType = 0x0,
    .advConfig.bStrictLenFilter = 0x0,
    .advConfig.bDirected = 0x0,
    .advConfig.privIgnMode = 0x0,
    .advConfig.rpaMode = 0x0,
    .__dummy0 = 0x00,
    .auxPtrTargetType = 0x00,
    .auxPtrTargetTime = 0x00000000,
    .pAdvPkt = 0, // INSERT APPLICABLE POINTER: (uint8_t*)&xxx
    .pRspPkt = 0, // INSERT APPLICABLE POINTER: (uint8_t*)&xxx
    .pDeviceAddress = 0, // INSERT APPLICABLE POINTER: (uint16_t*)&xxx
    .pWhiteList = 0, // INSERT APPLICABLE POINTER: (uint32_t*)&xxx
};

// CMD_BLE5_ADV_AUX
// Bluetooth 5 Secondary Channel Advertiser Command
rfc_CMD_BLE5_ADV_AUX_t RF_cmdBle5AdvAux =
{
    .commandNo = 0x1824,
    .status = 0x0000,
    .pNextOp = 0, // INSERT APPLICABLE POINTER: (uint8_t*)&xxx
    .startTime = 0x00000000,
    .startTrigger.triggerType = 0x0,
    .startTrigger.bEnaCmd = 0x0,
    .startTrigger.triggerNo = 0x0,
    .startTrigger.pastTrig = 0x0,
    .condition.rule = 0x1,
    .condition.nSkip = 0x0,
    .channel = 0x8C,
    .whitening.init = 0x51,
    .whitening.bOverride = 0x1,
    .phyMode.mainMode = 0x0,
    .phyMode.coding = 0x0,
    .rangeDelay = 0x00,
    .txPower = 0x9330,
    .pParams = &ble5AdvAuxPar,
    .pOutput = 0, // INSERT APPLICABLE POINTER: (uint8_t*)&xxx
};

// Structure for CMD_BLE5_SCANNER.pParams
rfc_ble5ScannerPar_t ble5ScannerPar =
{
 .pRxQ = NULL, // xxx insert pointer

 .rxConfig.bAutoFlushIgnored = 0,
 .rxConfig.bAutoFlushCrcErr = 0,
 .rxConfig.bAutoFlushEmpty = 0,
 .rxConfig.bIncludeLenByte = 1,
 .rxConfig.bIncludeCrc = 0,
 .rxConfig.bAppendRssi = 0,
 .rxConfig.bAppendStatus = 0,
 .rxConfig.bAppendTimestamp = 0,

 .scanConfig.scanFilterPolicy = 0,
 .scanConfig.bActiveScan = 0,
 .scanConfig.deviceAddrType = 0,
 .scanConfig.rpaFilterPolicy = 1, // TODO check this value
 .scanConfig.bStrictLenFilter = 0,
 .scanConfig.bAutoWlIgnore = 0,
 .scanConfig.bEndOnRpt = 1,
 .scanConfig.rpaMode = 0,

 .randomState = 1, // TODO check this value
 .backoffCount = 1,

 .backoffPar.logUpperLimit = 0,
 .backoffPar.bLastSucceeded = 0,
 .backoffPar.bLastFailed = 0,

 .extFilterConfig.bCheckAdi = 0,
 .extFilterConfig.bAutoAdiUpdate = 0,
 .extFilterConfig.bApplyDuplicateFiltering = 0,
 .extFilterConfig.bAutoWlIgnore = 0,

 .__dummy0 = 0,
 .pDeviceAddress = NULL,
 .pWhiteList = NULL,
 .pAdiList = NULL,
 .maxWaitTimeForAuxCh = 0, // TODO check this value

 .timeoutTrigger.triggerType = 0x1, // TODO check this value
 .timeoutTrigger.bEnaCmd = 0x0,
 .timeoutTrigger.triggerNo = 0x0,
 .timeoutTrigger.pastTrig = 0x0,

 .endTrigger.triggerType = 0x1,
 .endTrigger.bEnaCmd = 0x0,
 .endTrigger.triggerNo = 0x0,
 .endTrigger.pastTrig = 0x0,

 .timeoutTime = 0,
 .endTime = 0,
 .rxStartTime = 0,
 .rxListenTime = 0,
 .channelNo = 0x8C,
 .phyMode = 1,
};

// CMD_BLE5_SCANNER
// Bluetooth 5 Scanner Command
rfc_CMD_BLE5_SCANNER_t RF_cmdBle5Scanner =
{
    .commandNo = 0x1827,
    .status = 0x0000,
    .pNextOp = 0, // INSERT APPLICABLE POINTER: (uint8_t*)&xxx
    .startTime = 0x00000000,
    .startTrigger.triggerType = 0x0,
    .startTrigger.bEnaCmd = 0x0,
    .startTrigger.triggerNo = 0x0,
    .startTrigger.pastTrig = 0x0,
    .condition.rule = 0x1,
    .condition.nSkip = 0x0,
    .channel = 0x8C,
    .whitening.init = 0x51,
    .whitening.bOverride = 0x1,
    .phyMode.mainMode = 0x0,
    .phyMode.coding = 0x0,
    .rangeDelay = 0x00,
    .txPower = 0x9330,
    .pParams = &ble5ScannerPar,
    .pOutput = 0, // INSERT APPLICABLE POINTER: (uint8_t*)&xxx
};

// CMD_SYNC_STOP_RAT
// Synchronize and Stop Radio Timer Command
rfc_CMD_SYNC_STOP_RAT_t RF_cmdSyncStopRat =
{
    .commandNo = 0x0809,
    .status = 0x0000,
    .pNextOp = 0, // INSERT APPLICABLE POINTER: (uint8_t*)&xxx
    .startTime = 0x00000000,
    .startTrigger.triggerType = 0x0,
    .startTrigger.bEnaCmd = 0x0,
    .startTrigger.triggerNo = 0x0,
    .startTrigger.pastTrig = 0x0,
    .condition.rule = 0x0,
    .condition.nSkip = 0x0,
    .__dummy0 = 0x0000,
    .rat0 = 0x00000000,
};

// CMD_SYNC_START_RAT
// Synchrously Start Radio Timer Command
rfc_CMD_SYNC_START_RAT_t RF_cmdSyncStartRat =
{
    .commandNo = 0x080A,
    .status = 0x0000,
    .pNextOp = 0, // INSERT APPLICABLE POINTER: (uint8_t*)&xxx
    .startTime = 0x00000000,
    .startTrigger.triggerType = 0x0,
    .startTrigger.bEnaCmd = 0x0,
    .startTrigger.triggerNo = 0x0,
    .startTrigger.pastTrig = 0x0,
    .condition.rule = 0x0,
    .condition.nSkip = 0x0,
    .__dummy0 = 0x0000,
    .rat0 = 0x00000000,
};

// Structure for CMD_BLE_SCANNER.pParams
rfc_bleScannerPar_t bleScannerPar =
{
    .pRxQ = 0, // INSERT APPLICABLE POINTER: (dataQueue_t*)&xxx
    .rxConfig.bAutoFlushIgnored = 0x0,
    .rxConfig.bAutoFlushCrcErr = 0x0,
    .rxConfig.bAutoFlushEmpty = 0x0,
    .rxConfig.bIncludeLenByte = 0x0,
    .rxConfig.bIncludeCrc = 0x0,
    .rxConfig.bAppendRssi = 0x0,
    .rxConfig.bAppendStatus = 0x0,
    .rxConfig.bAppendTimestamp = 0x0,
    .scanConfig.scanFilterPolicy = 0x0,
    .scanConfig.bActiveScan = 0x0,
    .scanConfig.deviceAddrType = 0x0,
    .scanConfig.rpaFilterPolicy = 0x0,
    .scanConfig.bStrictLenFilter = 0x0,
    .scanConfig.bAutoWlIgnore = 0x0,
    .scanConfig.bEndOnRpt = 0x0,
    .scanConfig.rpaMode = 0x0,
    .randomState = 0x0000,
    .backoffCount = 0x0000,
    .backoffPar.logUpperLimit = 0x0,
    .backoffPar.bLastSucceeded = 0x0,
    .backoffPar.bLastFailed = 0x0,
    .scanReqLen = 0x00,
    .pScanReqData = 0, // INSERT APPLICABLE POINTER: (uint8_t*)&xxx
    .pDeviceAddress = 0, // INSERT APPLICABLE POINTER: (uint16_t*)&xxx
    .pWhiteList = 0, // INSERT APPLICABLE POINTER: (uint32_t*)&xxx
    .__dummy0 = 0x0000,
    .timeoutTrigger.triggerType = 0x0,
    .timeoutTrigger.bEnaCmd = 0x0,
    .timeoutTrigger.triggerNo = 0x0,
    .timeoutTrigger.pastTrig = 0x0,
    .endTrigger.triggerType = 0x0,
    .endTrigger.bEnaCmd = 0x0,
    .endTrigger.triggerNo = 0x0,
    .endTrigger.pastTrig = 0x0,
    .timeoutTime = 0x00000000,
    .endTime = 0x00000000,
};
